FROM node:22.23.2-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-audit --no-fund
EXPOSE 3000
CMD ["npm", "run", "dev"]
