"use client";
import { FormEvent, useEffect, useState } from "react";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
type Run = { id: string; status: string; taskCapability: string; modelProfile: string; modelReason: string; result?: { analysis?: string; artifact?: { id: string; filename: string } } };
export default function Home() {
  const [token, setToken] = useState(""); const [email, setEmail] = useState("admin@sih.local"); const [password, setPassword] = useState("ChangeMe123!"); const [workspaceId, setWorkspaceId] = useState(""); const [task, setTask] = useState("Read this inspection report and draft an approval note with the key findings."); const [file, setFile] = useState<File | null>(null); const [run, setRun] = useState<Run | null>(null); const [message, setMessage] = useState("");
  const headers = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
  async function login(event: FormEvent) { event.preventDefault(); const response = await fetch(`${api}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error?.message ?? "Login failed"); setToken(data.token); setMessage("Signed in. Create or select a workspace."); }
  async function createWorkspace() { const response = await fetch(`${api}/api/workspaces`, { method: "POST", headers, body: JSON.stringify({ name: "Inspection Review Workspace" }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error?.message ?? "Workspace creation failed"); setWorkspaceId(data.workspace.id); setMessage("Workspace ready."); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!workspaceId) return setMessage("Create a workspace first."); let artifactId: string | undefined; if (file) { const form = new FormData(); form.append("file", file); const upload = await fetch(`${api}/api/workspaces/${workspaceId}/artifacts`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); const data = await upload.json(); if (!upload.ok) return setMessage(data.error?.message ?? "Upload failed"); artifactId = data.artifact.id; } const response = await fetch(`${api}/api/workspaces/${workspaceId}/runs`, { method: "POST", headers, body: JSON.stringify({ task, artifactId }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error?.message ?? "Run failed"); setRun(data.run); setMessage("Run started. The trace updates automatically."); }
  async function downloadArtifact(id: string, filename: string) { const response = await fetch(`${api}/api/artifacts/${id}/download`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) return setMessage("Artifact download failed"); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
  useEffect(() => { if (!run || ["COMPLETED", "FAILED", "CANCELLED"].includes(run.status)) return; const timer = setInterval(async () => { const response = await fetch(`${api}/api/runs/${run.id}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json(); if (data?.status) setRun(data); }, 1500); return () => clearInterval(timer); }, [run, token]);
  if (!token) return <main><h1>SIH-2026</h1><p>Sovereign Industrial AI Workbench</p><form onSubmit={login}><input value={email} onChange={(e) => setEmail(e.target.value)} /><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /><button>Sign in</button></form><p>{message}</p></main>;
  return <main><header><div><h1>SIH-2026 Workbench</h1><p>On-premise agent runs, source-grounded deliverables, and auditable tools.</p></div><span className="badge">Development provider mode — non-sovereign</span></header><section className="panel"><button onClick={createWorkspace}>Create demo workspace</button>{workspaceId && <code>{workspaceId}</code>}</section><form className="panel" onSubmit={submit}><label>Task<textarea value={task} onChange={(e) => setTask(e.target.value)} /></label><label>Inspection report / image<input type="file" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><button>Run workbench task</button></form><p>{message}</p>{run && <section className="panel"><h2>Run trace</h2><p><b>{run.status}</b> · capability: {run.taskCapability} · model: {run.modelProfile}</p><p>{run.modelReason}</p>{run.result?.analysis && <pre>{run.result.analysis}</pre>}{run.result?.artifact && <button type="button" onClick={() => downloadArtifact(run.result!.artifact!.id, run.result!.artifact!.filename)}>Download {run.result.artifact.filename}</button>}</section>}<footer>All production services run on the internal Docker network. OpenRouter is a temporary development adapter only.</footer></main>;
}
